### ISSUE TITLE
Everytime I run it this show up

### ISSUE THREAD

**Issue by acepirine** [justinsadakhom/Mitsuku#1]
Every time I run it an open blank page in chrome shows up called ;data and then my bot comes online but nothing happens if I talk to it, can you please make a detailed tutorial on how to run this and tailor it to your needs?

**Comment by justin-sadakhom** [comment]
Hi, I just shipped a fix for the issue you were experiencing. Try updating your local repository and test out the chat functionality.

I'm more than happy to create a tutorial on how to set up the bot. What do you mean when you say tailor it to your needs? There isn't much you can do with this program other than chat with Mitsuku.

**Comment by justin-sadakhom** [comment]
I've realized why your bot isn't working when you try to talk to it.

When you create your bot in Discord, there should be an interface to get the token for your bot. You need to write the following line of code to the end of the main method in mitsuku.py

`bot.run([your token as a string])`

After this, the bot should work. I'll update the README and mitsuku.py comments to reflect this. Let me know how it goes!

**Comment by funkrusher** [comment]
Hi guys, 

just want to share my Dockerfile and Docker-Compose file...

maybe it can help someone

the bot works good! thx.

Dockerfile
```
FROM python:3.8

# Adding trusting keys to apt for repositories
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
# Adding Google Chrome to the repositories
RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
# Updating apt to see and install Google Chrome
RUN apt-get -y update
# Magic happens
RUN apt-get install -y google-chrome-stable

# Installing Unzip
RUN apt-get install -yqq unzip curl
# Download the Chrome Driver
RUN wget -O /tmp/chromedriver.zip http://chromedriver.storage.googleapis.com/`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`/chromedriver_linux64.zip
RUN unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/
# Set display port as an environment variable
ENV DISPLAY=:99

# Copy the source code in last to optimize rebuilding the image
COPY . /app

# Create the working directory
WORKDIR /app/bot

# Install project dependencies
RUN pip install -r requirements.txt
RUN pip install webdriver_manager
RUN pip install selenium

CMD ["python","-u","mitsuku.py"]
```

docker-compose.yml
```
version: "3.7"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
      
```

Also i needed following changes in code:
```
    print("init driver")
    # Configure headless instance of driver.
    chrome_options = Options()
    chrome_options.add_argument('--headless')
    chrome_options.add_argument('--no-sandbox')
    chrome_options.add_argument('--disable-dev-shm-usage')
    
    # Initialize driver to click button to activate widget.
    driver = webdriver.Chrome(ChromeDriverManager().install(), chrome_options=chrome_options)
```

The bot currently crashes if someone makes a Smiley in discord. Would be good to have a try/catch around the chat-message, so the bot does not crash completely or something like that. Greets.

**Comment by Craftyqt** [comment]
switching to webdriver.Firefox fixes the smiley crash issue, I haven't managed to cleanup the code through. Sharing in case it might help someone. :)

```python
from discord import Client
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support import ui
from webdriver_manager.firefox import GeckoDriverManager
from selenium.webdriver.firefox.options import Options as FirefoxOptions

def init_driver() -> webdriver:

    # Configure headless instance of driver.
    options = FirefoxOptions()
    options.add_argument("--headless")
    firefoxPath="/usr/bin/geckodriver" 
    #self.driver = webdriver.Firefox(executable_path=firefoxPath) 

    # Initialize driver to click button to activate widget.
    driver = webdriver.Firefox(executable_path=firefoxPath, options=options)
    print ("Headless Firefox Initialized")
    return driver
```

**Comment by funkrusher** [comment]
thanks :)

i can share my code. I have put in Try Catch so kuki prints a message "im irritated but will be right back" if something does not work and automatically will crash the docker-container in that case (because the chromedriver will be crappy after an error and may not work on).... the container will restart automatically and kuki will be back...

see my zip.
[mitsuku-master.zip](https://github.com/justinsadakhom/Mitsuku/files/5897953/mitsuku-master.zip)

**Comment by Craftyqt** [comment]
Much appreciated! Thanks for sharing funkrusher 🤗

**Comment by justin-sadakhom** [comment]
Thank you everyone for the contributions!

Heinral, I've changed the bot to use geckodriver as the new web driver. This seems to have fixed the issues with emojis. Thank you again!
